version: '3'
services:
  cache:
    image: 'redis:7.0-rc1-alpine3.15'
    expose:
    - 6379
  blogapp:
    depends_on:
     - cache
    env_file:
    - .env
    build: .
    ports:
    - '0.0.0.0:80:80'